# 기본 환경 선택
spring:
  profiles:
    active: local

# 운영 환경
---
spring:
  profiles: release
  profiles.include: private
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 443


# local 환경
---
spring:
  profiles: local
  profiles.include: private, google
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.format_sql: true
  data:
    rest:
      base-path: /api
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
server:
  port: 8081


